### ISSUE TITLE
Fingerprint Database

### ISSUE THREAD

**Issue by hazcod** [salesforce/hassh#3]
Hello,

are there any plans to start a database of known fingerprints?

**Comment by benreardon-sfdc** [comment]
Hi @hazcod, apologies for the delay, There are groups such as Shodan and GreyNoise who do make hasshServer available to search. We'd be interested to hear if anyone is collecting and sharing hassh data. Those related to internet scanners (collected by sensors) would be interesting to see shared. One issue that should be considered is that information would likely be shared just like with most Indicators - on an "all care taken, use at own risk" basis.
