### ISSUE TITLE
Bro 2.6 will fix SSH capabilities "is_server" flag

### ISSUE THREAD

**Issue by jsiwek** [salesforce/hassh#4]
The bug fix at https://github.com/zeek/zeek/pull/191 now allows these workarounds to be updated:

https://github.com/salesforce/hassh/blob/a9f1854727a5676593dcc7438448e51f76979330/bro/hassh.bro#L114-L133

If you want things to keep working with both Bro 2.5.x and 2.6, you should be able to branch on `Version::info`.

**Comment by benreardon-sfdc** [comment]
Thank you @jsiwek. added version checking logic to main script.
https://github.com/salesforce/hassh/blob/3fbd7f088079d6c4d2bcb4a915ebb41fca80b6e2/bro/hassh.bro#L114-L130
